"""add_cirurgia_finalizada_flags

Revision ID: 0c0061cfd60a
Revises: fd7e2ba37ca1
Create Date: 2026-05-25 14:19:19.831918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0061cfd60a'
down_revision: Union[str, Sequence[str], None] = 'fd7e2ba37ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes_leito', sa.Column('cirurgia_finalizada', sa.Boolean(), nullable=True, server_default=sa.text('0')))
    op.add_column('solicitacoes_leito', sa.Column('encaminhamento_liberado', sa.Boolean(), nullable=True, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitacoes_leito', 'encaminhamento_liberado')
    op.drop_column('solicitacoes_leito', 'cirurgia_finalizada')
    # ### end Alembic commands ###
