"""add_lido_em_and_lido_por_to_alertas

Revision ID: 1c7debc81e99
Revises: 6cea0d40dcd9
Create Date: 2026-07-28 11:21:56.834001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7debc81e99'
down_revision: Union[str, Sequence[str], None] = '6cea0d40dcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertas', sa.Column('lido_em', sa.DateTime(), nullable=True))
    op.add_column('alertas', sa.Column('lido_por', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alertas', 'lido_por')
    op.drop_column('alertas', 'lido_em')
    # ### end Alembic commands ###
