"""add_ad_details_to_usuario_perfil

Revision ID: 6cea0d40dcd9
Revises: 0c0061cfd60a
Create Date: 2026-07-07 15:31:16.842342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_ad_details_to_usuario_perfil

Revision ID: 6cea0d40dcd9
Revises: 0c0061cfd60a
Create Date: 2026-07-07 15:31:16.842342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cea0d40dcd9'
down_revision: Union[str, Sequence[str], None] = '0c0061cfd60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios_perfis', sa.Column('nome_completo', sa.String(length=100), nullable=True))
    op.add_column('usuarios_perfis', sa.Column('lotacao', sa.String(length=100), nullable=True))
    op.add_column('usuarios_perfis', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios_perfis', 'email')
    op.drop_column('usuarios_perfis', 'lotacao')
    op.drop_column('usuarios_perfis', 'nome_completo')
    # ### end Alembic commands ###
